<footer class="home-footer">
  <div class="shell home-footer__grid">
    <div><p class="home-footer__title">Company</p><nav aria-label="Footer navigation"><a href="<?php echo esc_url(home_url('/')); ?>">Home</a><a href="<?php echo esc_url(home_url('/about/')); ?>">About</a><a href="<?php echo esc_url(home_url('/advertise/')); ?>">Advertise</a><a href="<?php echo esc_url(home_url('/#services')); ?>">Services</a><a href="<?php echo esc_url(home_url('/past-work/')); ?>">Past Work</a><a href="<?php echo esc_url(home_url('/#team')); ?>">Team</a><a href="<?php echo esc_url(gtvafrik_posts_page_url()); ?>">News</a><a href="<?php echo esc_url(home_url('/contact-us/')); ?>">Contact</a><a href="<?php echo esc_url(home_url('/book-a-call/')); ?>">Book a Call</a></nav></div>
    <div><p class="home-footer__title">We Are Available 24/7. Call Now.</p><a href="tel:+2348188059300">+234 818 805 9300</a><a href="mailto:info@gtvafrik.com">info@gtvafrik.com</a><p class="home-footer__title home-footer__social-title">Find us here</p><div class="home-footer__social"><a href="https://www.facebook.com/share/1Dbq4Fbc1C/?mibextid=wwXIfr" target="_blank" rel="noopener noreferrer" aria-label="GTVAFRIK on Facebook">f</a><a href="https://www.instagram.com/gtvafrik_original?stkn=MWx0bW5paWM5MGtxcw==" target="_blank" rel="noopener noreferrer" aria-label="GTVAFRIK on Instagram">◎</a><a href="https://youtube.com/@gtvafrikoriginal?si=vHEf26I4gNznPtxh" target="_blank" rel="noopener noreferrer" aria-label="GTVAFRIK on YouTube">▶</a></div></div>
    <div><p class="home-footer__title">Contact Information</p><address><strong>West Africa</strong><br>Suite 38, Birgi Plaza, Wuye, Nigeria<br><br><strong>South Africa</strong><br>The Business Centre, Fourways, South Africa<br><br><strong>North Africa</strong><br>21C Street 198, Maadi, Egypt</address></div>
  </div>
  <div class="home-footer__legal"><div class="shell"><nav><a href="<?php echo esc_url(home_url('/disclaimer/')); ?>">Disclaimer</a><a href="<?php echo esc_url(home_url('/cookies-policy/')); ?>">Cookies Policy</a><a href="<?php echo esc_url(home_url('/privacy-policy/')); ?>">Privacy Policy</a><a href="<?php echo esc_url(home_url('/terms-of-use/')); ?>">Terms of Use</a></nav><p>Copyright © 2026 GTV Afrik | All Rights Reserved</p></div></div>
</footer>

